### ISSUE TITLE
Large files

### ISSUE THREAD

**Issue by PeterGerrard** [timadye/werewolf#10]
The client javascript file is getting rather large, it would be nice to split up based on the current game state (e.g. have separate files for lobby, day and nighttime).

This will make it easier to understand what is available at each different state.

**Comment by timadye** [comment]
I agree.
Unfortunately I couldn't get JS to do this handily.
It seems to require you to put everything in a separate file in a namespace and/or import everything by name.
I found a really ugly workaround that I used for utils.js, but that soured me to the idea. I dropped it for the time being.

**Comment by timadye** [comment]
I have now split the `.js` and `.html` files into smaller chunks based on their function. I didn't want to have to `import` everything everywhere, so I defined all functions (and a few variables) global by setting them as global variables.
